# Generated by Django 2.1.3 on 2018-11-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_title', models.CharField(max_length=250)),
                ('ep_file', models.FileField(upload_to='')),
                ('ep_release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shw_title', models.CharField(max_length=250)),
                ('shw_slug', models.SlugField(unique=True)),
                ('shw_hosts', models.CharField(max_length=250)),
                ('shw_icon', models.FileField(upload_to='')),
                ('shw_desc', models.CharField(max_length=1000, null='false')),
                ('shw_live_on_time', models.TimeField(blank=True, null=True)),
                ('shw_live_off_time', models.TimeField(blank=True, null=True)),
                ('shw_days', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=250)),
                ('st_slug', models.SlugField(unique=True)),
                ('st_icon', models.FileField(upload_to='')),
                ('st_freq', models.CharField(max_length=100)),
                ('st_live', models.CharField(max_length=1000)),
                ('st_tagline', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='shw_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Station'),
        ),
        migrations.AddField(
            model_name='episode',
            name='ep_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Show'),
        ),
    ]
