# Generated by Django 2.1.2 on 2018-11-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='shw_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Station'),
        ),
    ]
