# Generated by Django 2.1.3 on 2018-12-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='shw_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='st_slug',
            new_name='slug',
        ),
    ]
