# Generated by Django 2.1.2 on 2018-11-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20181103_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='ep_release_date',
            field=models.DateField(blank=True, null=True, verbose_name='DOR'),
        ),
    ]
