# Generated by Django 2.1.3 on 2018-12-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20181206_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='st_desc',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
