# Generated by Django 2.1.2 on 2018-11-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_episode_ep_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='ep_release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date'),
        ),
    ]
