# Generated by Django 2.1.3 on 2019-05-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_episode_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='slug',
        ),
    ]
