# Generated by Django 2.1.2 on 2018-11-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20181103_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='shw_live_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='shw_live_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
