# Generated by Django 2.1.2 on 2018-11-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_auto_20181103_1505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='DoW',
        ),
    ]
