# Generated by Django 2.1.2 on 2018-11-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_auto_20181103_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='shw_days',
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
