# Generated by Django 2.1.2 on 2018-11-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_auto_20181103_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='days',
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
