# Generated by Django 2.1.2 on 2018-11-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0015_auto_20181103_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='days',
            new_name='shw_days',
        ),
    ]
