# Generated by Django 2.1.2 on 2018-11-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0016_auto_20181103_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='shw_desc',
            field=models.CharField(max_length=1000, null='true'),
            preserve_default='true',
        ),
    ]
