# Generated by Django 2.1.2 on 2018-11-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0017_show_shw_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='shw_desc',
        ),
    ]
