# Generated by Django 2.1.2 on 2018-11-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0025_show_shw_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='shw_desc',
            field=models.CharField(max_length=1000, null='false'),
        ),
    ]
