# Generated by Django 2.1.3 on 2018-11-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0026_auto_20181103_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='ep_file_type',
        ),
        migrations.AddField(
            model_name='episode',
            name='ep_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='shw_icon',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='station',
            name='st_icon',
            field=models.FileField(upload_to=''),
        ),
    ]
