# Generated by Django 2.1.3 on 2018-11-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0027_auto_20181121_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='st_live',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
